Bugfix update to glib2-2.28.3.
Fixes the following:
* 644465 undefined reference to `_usleep'
* 644552 g_timeout_add_seconds(1, ...) may have a latency...
* 644607 correct internal definition of C_()